In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
if __name__ == '__main__':
    #加载数据集
    iris = load_iris()
    data = iris.get("data")
    target = iris.get("target")
    
    #将数据集划分为0.8的训练数据集 0.2 的测试数据集
    x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=0)
    print(x_test) 
    print("-------------------")
    print(y_test)
    
    #将最近的点位个数设置为5个 
    #就是通过距离该点最近的五个个体 进行类型判断 哪种占比越大 该个体就被划分为那种个图 
    KNN = KNeighborsClassifier(n_neighbors=5)
    KNN.fit(x_train, y_train)
    train_score = KNN.score(x_train, y_train)
    test_score = KNN.score(x_test, y_test)
    print("模型的准确率：", test_score)
    


    

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]]
-------------------
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
模型的准确率： 0.9666666666666667


In [2]:
    
    #test数据集检验 将分类类型与实际类型进行比对    
    cnt=0
    for x in x_test:
        prediction =KNN.predict([x]) 
        k = iris.get("target_names")[prediction]
        
        label_idx=y_test[cnt]
        if label_idx==0: 
            label="setosa"
        elif label_idx==1:
            label="versicolor"
        else:
            label="virginica"
        
        cnt+=1
        print(cnt,"花的预测种类为：",k,"花的实际种类为:",label)

1 花的预测种类为： ['virginica'] 花的实际种类为: virginica
2 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
3 花的预测种类为： ['setosa'] 花的实际种类为: setosa
4 花的预测种类为： ['virginica'] 花的实际种类为: virginica
5 花的预测种类为： ['setosa'] 花的实际种类为: setosa
6 花的预测种类为： ['virginica'] 花的实际种类为: virginica
7 花的预测种类为： ['setosa'] 花的实际种类为: setosa
8 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
9 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
10 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
11 花的预测种类为： ['virginica'] 花的实际种类为: virginica
12 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
13 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
14 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
15 花的预测种类为： ['virginica'] 花的实际种类为: versicolor
16 花的预测种类为： ['setosa'] 花的实际种类为: setosa
17 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
18 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
19 花的预测种类为： ['setosa'] 花的实际种类为: setosa
20 花的预测种类为： ['setosa'] 花的实际种类为: setosa
21 花的预测种类为： ['virginica'] 花的实际种类为: virginica
22 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
23 花的预测种类为： ['setosa'] 花的实际种类为: se

![](https://ai-studio-static-online.cdn.bcebos.com/32158ffa77a64428aaba4e8193cf1a0a3df59d0461c44fbb9bffeffa9173366a)
![](https://ai-studio-static-online.cdn.bcebos.com/aaabefe7d5794f149949c4be98619a2a67a4142300534a9995d7c6fe18a0aeca)


In [3]:
#将最近“邻居”个数调到6 个 ，模型预测准确性达到1 （训练集，测试数据集较少） 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
if __name__ == '__main__':
    #加载数据集
    iris = load_iris()
    data = iris.get("data")
    target = iris.get("target")
    
    #将数据集划分为0.8的训练数据集 0.2 的测试数据集
    x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=0)
    print(x_test) 
    print("-------------------")
    print(y_test)
    
    #将最近的点位个数设置为5个 
    #就是通过距离该点最近的五个个体 进行类型判断 哪种占比越大 该个体就被划分为那种个图 
    KNN = KNeighborsClassifier(n_neighbors=6)
    KNN.fit(x_train, y_train)
    train_score = KNN.score(x_train, y_train)
    test_score = KNN.score(x_test, y_test)
    print("模型的准确率：", test_score)
    

    
    #test数据集检验 将分类类型与实际类型进行比对    
    cnt=0
    for x in x_test:
        prediction =KNN.predict([x]) 
        k = iris.get("target_names")[prediction]
        
        label_idx=y_test[cnt]
        if label_idx==0: 
            label="setosa"
        elif label_idx==1:
            label="versicolor"
        else:
            label="virginica"
        
        cnt+=1
        print(cnt,"花的预测种类为：",k,"花的实际种类为:",label)

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]]
-------------------
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
模型的准确率： 1.0
1 花的预测种类为： ['virginica'] 花的实际种类为: virginica
2 花的预测种类为： ['versicolor'] 花的实际种类为: versicolor
3 花的预测种类为： ['setosa'] 花的实际种类为: setosa
4 花的预测种类为： ['virginica'] 花的实际种类为: virginica
5 花的预测种类为： ['setosa'] 花的实际种类为: setosa
6 花的预测种类为： ['virginica'] 花的实际种类为: virginica
7 花的预测种类为： ['setosa'] 花的实际种类为: setosa
8 花的预测种类为： ['versicolor'] 花的实际种类为: versicol

![](https://ai-studio-static-online.cdn.bcebos.com/5d8198d98e664931a9cc287e355b7c90b38094d4e7264875a1ea4e13a909d910)
